import UserIcon from '@/assets/icons/1.svg'
import SearchIcon from '@/assets/icons/2.svg'
import WishlistIcon from '@/assets/icons/3.svg'
import CartIcon from '@/assets/icons/3.svg'
import Logo from '@/assets/icons/logo.png'
import Logo_footer from '@/assets/icons/Logo_white.png'
import Cart_1 from '@/assets/icons/mastercard_v1.png'
import Cart_2 from '@/assets/icons/mastercard_v2.png'
import Cart_3 from '@/assets/icons/mastercard_v3.png'
import Cart_4 from '@/assets/icons/mastercard_v4.png'
import Truck from '@/assets/icons/truck-fast.png'
import Safe from '@/assets/icons/safe-home.png'
import Coin from '@/assets/icons/coin.png'
export { UserIcon, SearchIcon, WishlistIcon, CartIcon, Logo, Logo_footer, Cart_1, Cart_2, Cart_3, Cart_4, Truck, Safe, Coin }
